name: VoteBan
description: vote for bans and ban players without moderators
main: me.nelson131.voteban.VoteBan
version: 1.1.0
author: nelson131
commands:
  voteban:
    description: create a voteban poll
  vote:
    description: vote for somebody
  players:
    description: get the list of players with count of total,afk and without afk
permissions:
  voteban.immune:
    description: immunity for player